ros2_rag:
  ros__parameters:
    generator_family: 'qwen'
    generator_version: 'tiny'
    generator_loading: 'pretrained'
    knowledge_base_path: '/home/ubuntu/knowledge_base'
    retriever:
      top_k: 5
      alpha: 0.6
    generator:
      max_new_tokens: 75
      temperature: 0.5
      top_p: 0.9
    history_active: true
    history:
      recent_interaction_number: 2
      evicted_interaction_number: 4
    format:
      remove_bullets: true
    rag_verification_active: true
    rag_verification:
      entailment_threshold: 0.75
